#!/home/emil/.pyenv/shims/python
"""Generate a password using correct horse battery staple algorithm.

Usage:
  strong-password <length> [--delimiter=<delimiter>] [--stupid]

Options:
  -h --help    Show this screen.
  --version    Show version.
  --delimiter=<delimiter>  Choose word delimiter [default: -]
  --stupid     Password contains at least one capital letter and a number
  
"""
import math
import re
import sys
from secrets import SystemRandom

from docopt import docopt
from termcolor import colored

arguments = docopt(__doc__, version='Generate password 3')
length = int(arguments["<length>"])
delimiter = arguments["--delimiter"]
stupid = arguments["--stupid"]
file = "/usr/share/dict/words"

ascii_only = re.compile("^[a-z]*$").match
common_plural = re.compile(".*(er|ar|s|na)$").match

with open(file, encoding="iso-8859-1") as d:
    words = {
        word.strip()
        for word in d
        if not ascii_only(word)
        if not common_plural(word)
    }

rng = SystemRandom()
passwords = rng.sample(words, length)
if stupid:
    passwords.append("Z8")

result = delimiter.join(passwords)

# Quality measurement
entropy = len(words) ** length
bits = int(math.log(entropy, 2))
same_as = int(math.log(entropy, 62))

quality = f"Password strength: {bits} bits, same as {same_as} character password\n"

sys.stderr.write(colored(quality, "yellow"))
print(result)
