#!/usr/bin/python3
"""Generate a password using correct horse battery staple algorithm.

Usage:
  strong-password <length> [--delimiter=<delimiter>] [--stupid]

Options:
  -h --help    Show this screen.
  --version    Show version.
  --delimiter=<delimiter>  Choose word delimiter [default: -]
  --stupid     Password contains at least one capital letter and a number
  
"""
import math
import re
import sys
from secrets import choice

from docopt import docopt
from termcolor import colored

arguments = docopt(__doc__, version='Generate password 2')
length = int(arguments["<length>"])
delimiter = arguments["--delimiter"]
stupid = arguments["--stupid"]
file = "/usr/share/dict/words"

words = set()
ascii_only = re.compile("^[a-z]*$").match
common_plural = re.compile(".*(er|ar|s|na)$").match

with open(file, encoding="iso-8859-1") as d:
    for word in d:
        word = word.strip()
        if not ascii_only(word):
            continue
        if common_plural(word):
            continue
        words.add(word)

passwords = [choice(words) for _ in range(length)]
if stupid:
    passwords.append("Z8")

result = delimiter.join(passwords)

# Quality measurement
entropy = len(words) ** length
bits = int(math.log(entropy, 2))
same_as = int(math.log(entropy, 62))

quality = f"Password strength: {bits} bits, same as {same_as} character password\n"

sys.stderr.write(colored(quality, "yellow"))
print(result)
